# Compile project on Ubuntu
name: Ubuntu
on:
  push:
    paths:
      - "**"
      - "!.github/**"
      - ".github/workflows/Ubuntu.yml"
      - "!scripts/**"
      - "scripts/actions/install_hip_ubuntu.sh"
      - "!*.md"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          - os: ubuntu-24.04
            hip: "7.2"
          - os: ubuntu-24.04
            hip: "7.0"
    env:
      build_dir: "build"
      config: "Release"
  
    steps:

    - uses: actions/checkout@v6

    - name: Install HIP
      env:
        hip: ${{ matrix.hip }}
      run: ./scripts/actions/install_hip_ubuntu.sh
      shell: bash

    - name: Configure cmake
      id: configure
      run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }}

    - name: Configure Error Processing
      if: ${{ failure() && steps.configure.outcome == 'failure' }}
      run: |
          if [[ -d "${{ env.build_dir }}" ]]; then
            pushd "${{ env.build_dir }}"
            if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
              echo "---- CMakeFiles/CMakeOutput.log"
              cat CMakeFiles/CMakeOutput.log
              echo "----"
            fi
            if [[ -f "CMakeFiles/CMakeError.log" ]]; then
              echo "---- CMakeFiles/CMakeError.log"
              cat CMakeFiles/CMakeError.log
              echo "----"
            fi
          fi

    - name: Build
      working-directory: ${{ env.build_dir }}
      run: cmake --build . --target all --verbose -j `nproc`